create table if not exists public.premium_content (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null default '',
  body text not null default '',
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.premium_content enable row level security;

revoke all on table public.premium_content from anon;
revoke all on table public.premium_content from authenticated;
grant select on table public.premium_content to authenticated;

drop policy if exists "Premium users can read published content" on public.premium_content;

create policy "Premium users can read published content"
on public.premium_content for select to authenticated
using (
  published = true
  and exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role in ('premium','admin')
  )
);

create index if not exists idx_premium_content_published_created
on public.premium_content(published, created_at desc);