-- AHORRAENCASAYA - ANALISIS PREMIUM DE CLIMATIZACION
create table if not exists public.climate_analyses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  season text not null default 'verano' check (season in ('verano','invierno','todo')),
  system_type text not null default 'bomba_calor' check (system_type in ('aire_acondicionado','bomba_calor','radiador_electrico','caldera','otro')),
  room_area_m2 numeric(10,2) not null default 60 check (room_area_m2 >= 0),
  setpoint_c numeric(5,2) not null,
  outdoor_c numeric(5,2) not null,
  hours_day numeric(6,2) not null check (hours_day >= 0),
  days_year integer not null default 180 check (days_year between 1 and 366),
  input_power_kw numeric(8,3) not null check (input_power_kw >= 0),
  electricity_price numeric(8,4) not null default 0.20 check (electricity_price >= 0),
  baseline_hours_day numeric(6,2) not null default 0 check (baseline_hours_day >= 0),
  baseline_power_kw numeric(8,3) not null default 0 check (baseline_power_kw >= 0),
  baseline_cost numeric(12,2) not null default 0 check (baseline_cost >= 0),
  optimized_cost numeric(12,2) not null default 0 check (optimized_cost >= 0),
  annual_saving numeric(12,2) not null default 0 check (annual_saving >= 0),
  efficiency_factor numeric(8,3) not null default 1 check (efficiency_factor > 0),
  maintenance_cost numeric(12,2) not null default 0 check (maintenance_cost >= 0),
  improvement_cost numeric(12,2) not null default 0 check (improvement_cost >= 0),
  payback_years numeric(12,2),
  recommendation text not null default '',
  created_at timestamptz not null default now()
);

alter table public.climate_analyses enable row level security;
revoke all on table public.climate_analyses from anon;
revoke all on table public.climate_analyses from authenticated;
grant select, insert, update, delete on table public.climate_analyses to authenticated;
grant usage, select on sequence public.climate_analyses_id_seq to authenticated;

drop policy if exists "Premium users read own climate analyses" on public.climate_analyses;
create policy "Premium users read own climate analyses" on public.climate_analyses
for select to authenticated using (
  user_id = auth.uid() and exists (
    select 1 from public.profiles p where p.id=auth.uid() and p.role in ('premium','admin')
  )
);

drop policy if exists "Premium users insert own climate analyses" on public.climate_analyses;
create policy "Premium users insert own climate analyses" on public.climate_analyses
for insert to authenticated with check (
  user_id = auth.uid() and exists (
    select 1 from public.profiles p where p.id=auth.uid() and p.role in ('premium','admin')
  )
);

drop policy if exists "Premium users update own climate analyses" on public.climate_analyses;
create policy "Premium users update own climate analyses" on public.climate_analyses
for update to authenticated using (
  user_id = auth.uid() and exists (
    select 1 from public.profiles p where p.id=auth.uid() and p.role in ('premium','admin')
  )
) with check (
  user_id = auth.uid() and exists (
    select 1 from public.profiles p where p.id=auth.uid() and p.role in ('premium','admin')
  )
);

drop policy if exists "Premium users delete own climate analyses" on public.climate_analyses;
create policy "Premium users delete own climate analyses" on public.climate_analyses
for delete to authenticated using (
  user_id = auth.uid() and exists (
    select 1 from public.profiles p where p.id=auth.uid() and p.role in ('premium','admin')
  )
);

create index if not exists idx_climate_analyses_user_created
on public.climate_analyses(user_id, created_at desc);