-- AHORRAENCASAYA - OPTIMIZADOR DE POTENCIA CONTRATADA

create table if not exists public.power_optimizations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  contracted_power numeric(8,3) not null check (contracted_power > 0),
  peak_power numeric(8,3) check (peak_power is null or peak_power >= 0),
  annual_power_cost numeric(12,2) not null default 0 check (annual_power_cost >= 0),
  proposed_power numeric(8,3) check (proposed_power is null or proposed_power > 0),
  proposed_annual_cost numeric(12,2) check (proposed_annual_cost is null or proposed_annual_cost >= 0),
  safety_margin_pct numeric(6,2) not null default 20 check (safety_margin_pct between 0 and 100),
  notes text not null default '',
  created_at timestamptz not null default now()
);

alter table public.power_optimizations enable row level security;

revoke all on table public.power_optimizations from anon;
revoke all on table public.power_optimizations from authenticated;
grant select, insert, update, delete on table public.power_optimizations to authenticated;
grant usage, select on sequence public.power_optimizations_id_seq to authenticated;

drop policy if exists "Premium users read own power optimizations" on public.power_optimizations;
create policy "Premium users read own power optimizations"
on public.power_optimizations for select to authenticated
using (
  user_id = auth.uid()
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('premium','admin'))
);

drop policy if exists "Premium users insert own power optimizations" on public.power_optimizations;
create policy "Premium users insert own power optimizations"
on public.power_optimizations for insert to authenticated
with check (
  user_id = auth.uid()
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('premium','admin'))
);

drop policy if exists "Premium users update own power optimizations" on public.power_optimizations;
create policy "Premium users update own power optimizations"
on public.power_optimizations for update to authenticated
using (
  user_id = auth.uid()
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('premium','admin'))
)
with check (
  user_id = auth.uid()
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('premium','admin'))
);

drop policy if exists "Premium users delete own power optimizations" on public.power_optimizations;
create policy "Premium users delete own power optimizations"
on public.power_optimizations for delete to authenticated
using (
  user_id = auth.uid()
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('premium','admin'))
);

create index if not exists idx_power_optimizations_user_created
on public.power_optimizations(user_id, created_at desc);
