-- AHORRAENCASAYA - ECONOMIA DE ELECTRODOMESTICOS PREMIUM

create table if not exists public.appliance_analyses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  appliance_name text not null default 'Electrodoméstico',
  current_power_w numeric(10,2) not null check (current_power_w >= 0),
  current_hours_day numeric(8,2) not null check (current_hours_day >= 0),
  current_days_year integer not null default 365 check (current_days_year between 1 and 366),
  current_kwh_year numeric(12,2) not null check (current_kwh_year >= 0),
  current_energy_cost_year numeric(12,2) not null check (current_energy_cost_year >= 0),
  new_purchase_cost numeric(12,2) not null default 0 check (new_purchase_cost >= 0),
  new_power_w numeric(10,2) not null default 0 check (new_power_w >= 0),
  new_kwh_year numeric(12,2) not null default 0 check (new_kwh_year >= 0),
  new_energy_cost_year numeric(12,2) not null default 0 check (new_energy_cost_year >= 0),
  annual_energy_saving numeric(12,2) not null default 0 check (annual_energy_saving >= 0),
  payback_years numeric(12,2),
  saving_5_years numeric(12,2) not null default 0,
  saving_10_years numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  constraint appliance_name_length check (char_length(appliance_name) between 1 and 120)
);

alter table public.appliance_analyses enable row level security;
revoke all on table public.appliance_analyses from anon;
revoke all on table public.appliance_analyses from authenticated;
grant select, insert, update, delete on table public.appliance_analyses to authenticated;
grant usage, select on sequence public.appliance_analyses_id_seq to authenticated;

drop policy if exists "Premium users read own appliance analyses" on public.appliance_analyses;
create policy "Premium users read own appliance analyses"
on public.appliance_analyses for select to authenticated
using (
  user_id = auth.uid()
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('premium','admin'))
);

drop policy if exists "Premium users insert own appliance analyses" on public.appliance_analyses;
create policy "Premium users insert own appliance analyses"
on public.appliance_analyses for insert to authenticated
with check (
  user_id = auth.uid()
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('premium','admin'))
);

drop policy if exists "Premium users update own appliance analyses" on public.appliance_analyses;
create policy "Premium users update own appliance analyses"
on public.appliance_analyses for update to authenticated
using (
  user_id = auth.uid()
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('premium','admin'))
)
with check (
  user_id = auth.uid()
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('premium','admin'))
);

drop policy if exists "Premium users delete own appliance analyses" on public.appliance_analyses;
create policy "Premium users delete own appliance analyses"
on public.appliance_analyses for delete to authenticated
using (
  user_id = auth.uid()
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('premium','admin'))
);

create index if not exists idx_appliance_analyses_user_created
on public.appliance_analyses(user_id, created_at desc);
