-- Auditor de Factura Premium
create table if not exists public.premium_audits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  billing_days integer not null default 30 check (billing_days between 1 and 366),
  kwh numeric(12,3) not null default 0 check (kwh >= 0),
  total_bill numeric(12,2) not null default 0 check (total_bill >= 0),
  contracted_power numeric(8,3) not null default 0 check (contracted_power >= 0),
  energy_price numeric(10,6) not null default 0 check (energy_price >= 0),
  power_cost numeric(12,2) not null default 0 check (power_cost >= 0),
  fixed_services numeric(12,2) not null default 0 check (fixed_services >= 0),
  discounts numeric(12,2) not null default 0 check (discounts >= 0),
  previous_days integer check (previous_days is null or previous_days between 1 and 366),
  previous_kwh numeric(12,3) check (previous_kwh is null or previous_kwh >= 0),
  previous_bill numeric(12,2) check (previous_bill is null or previous_bill >= 0),
  notes text not null default '',
  created_at timestamptz not null default now()
);

alter table public.premium_audits enable row level security;
revoke all on table public.premium_audits from anon;
revoke all on table public.premium_audits from authenticated;
grant select, insert, update, delete on table public.premium_audits to authenticated;
grant usage, select on sequence public.premium_audits_id_seq to authenticated;

drop policy if exists "Premium users read own audits" on public.premium_audits;
drop policy if exists "Premium users insert own audits" on public.premium_audits;
drop policy if exists "Premium users update own audits" on public.premium_audits;
drop policy if exists "Premium users delete own audits" on public.premium_audits;

create policy "Premium users read own audits"
on public.premium_audits for select to authenticated
using (
  user_id = auth.uid()
  and exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role in ('premium','admin')
  )
);

create policy "Premium users insert own audits"
on public.premium_audits for insert to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role in ('premium','admin')
  )
);

create policy "Premium users update own audits"
on public.premium_audits for update to authenticated
using (
  user_id = auth.uid()
  and exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role in ('premium','admin')
  )
)
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role in ('premium','admin')
  )
);

create policy "Premium users delete own audits"
on public.premium_audits for delete to authenticated
using (
  user_id = auth.uid()
  and exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role in ('premium','admin')
  )
);

create index if not exists idx_premium_audits_user_created
on public.premium_audits(user_id, created_at desc);