-- Funcionalidad Premium: objetivos personales de ahorro
create table if not exists public.premium_goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Mi objetivo de ahorro',
  target_amount numeric(12,2) not null default 1000 check (target_amount >= 0),
  target_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id)
);

alter table public.premium_goals enable row level security;

revoke all on table public.premium_goals from anon;
revoke all on table public.premium_goals from authenticated;
grant select, insert, update, delete on table public.premium_goals to authenticated;
grant usage, select on sequence public.premium_goals_id_seq to authenticated;

drop policy if exists "Users can read own premium goal" on public.premium_goals;
drop policy if exists "Users can insert own premium goal" on public.premium_goals;
drop policy if exists "Users can update own premium goal" on public.premium_goals;
drop policy if exists "Users can delete own premium goal" on public.premium_goals;

create policy "Users can read own premium goal"
on public.premium_goals for select to authenticated
using (user_id = auth.uid());

create policy "Users can insert own premium goal"
on public.premium_goals for insert to authenticated
with check (user_id = auth.uid());

create policy "Users can update own premium goal"
on public.premium_goals for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "Users can delete own premium goal"
on public.premium_goals for delete to authenticated
using (user_id = auth.uid());

create index if not exists idx_premium_goals_user_id
on public.premium_goals(user_id);

alter table public.premium_goals
  add constraint premium_goals_title_length check (char_length(title) between 1 and 120);