-- AHORRAENCASAYA - SIMULADOR SOLAR PREMIUM
create table if not exists public.solar_analyses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  annual_consumption_kwh numeric(12,2) not null check (annual_consumption_kwh >= 0),
  daytime_share_pct numeric(6,2) not null default 40 check (daytime_share_pct between 0 and 100),
  system_kwp numeric(8,2) not null check (system_kwp > 0),
  specific_yield_kwh_kwp numeric(10,2) not null default 1500 check (specific_yield_kwh_kwp > 0),
  installation_cost numeric(12,2) not null check (installation_cost >= 0),
  self_consumption_pct numeric(6,2) not null default 60 check (self_consumption_pct between 0 and 100),
  energy_price numeric(8,4) not null default 0.20 check (energy_price >= 0),
  surplus_price numeric(8,4) not null default 0.05 check (surplus_price >= 0),
  annual_production_kwh numeric(12,2) not null default 0,
  annual_self_consumed_kwh numeric(12,2) not null default 0,
  annual_surplus_kwh numeric(12,2) not null default 0,
  annual_saving numeric(12,2) not null default 0,
  simple_payback_years numeric(12,2),
  created_at timestamptz not null default now()
);

alter table public.solar_analyses enable row level security;
revoke all on table public.solar_analyses from anon;
revoke all on table public.solar_analyses from authenticated;
grant select, insert, update, delete on table public.solar_analyses to authenticated;
grant usage, select on sequence public.solar_analyses_id_seq to authenticated;

drop policy if exists "Premium users read own solar analyses" on public.solar_analyses;
create policy "Premium users read own solar analyses"
on public.solar_analyses for select to authenticated
using (
 user_id = auth.uid()
 and exists (select 1 from public.profiles p where p.id=auth.uid() and p.role in ('premium','admin'))
);

drop policy if exists "Premium users insert own solar analyses" on public.solar_analyses;
create policy "Premium users insert own solar analyses"
on public.solar_analyses for insert to authenticated
with check (
 user_id = auth.uid()
 and exists (select 1 from public.profiles p where p.id=auth.uid() and p.role in ('premium','admin'))
);

drop policy if exists "Premium users update own solar analyses" on public.solar_analyses;
create policy "Premium users update own solar analyses"
on public.solar_analyses for update to authenticated
using (
 user_id = auth.uid()
 and exists (select 1 from public.profiles p where p.id=auth.uid() and p.role in ('premium','admin'))
)
with check (
 user_id = auth.uid()
 and exists (select 1 from public.profiles p where p.id=auth.uid() and p.role in ('premium','admin'))
);

drop policy if exists "Premium users delete own solar analyses" on public.solar_analyses;
create policy "Premium users delete own solar analyses"
on public.solar_analyses for delete to authenticated
using (
 user_id = auth.uid()
 and exists (select 1 from public.profiles p where p.id=auth.uid() and p.role in ('premium','admin'))
);

create index if not exists idx_solar_analyses_user_created
on public.solar_analyses(user_id, created_at desc);