-- Esquema de usuarios y administración de AhorraEnCasaYa
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'user' check (role in ('user','premium','admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- El cliente público no debe poder leer perfiles ajenos ni modificar roles.
revoke all on public.profiles from anon;
revoke insert, update, delete on public.profiles from authenticated;
grant select on public.profiles to authenticated;

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

-- El perfil se crea automáticamente al registrarse.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', ''));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- =========================================================
-- Administración protegida
-- Estas funciones comprueban el rol del usuario autenticado
-- dentro de la base de datos. No dependen de ocultar botones
-- ni de una clave secreta en el navegador.
-- =========================================================

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

revoke execute on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

create or replace function public.admin_list_profiles()
returns table (
  id uuid,
  full_name text,
  role text,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'Acceso restringido: se requiere rol admin';
  end if;

  return query
  select p.id, p.full_name, p.role, p.created_at
  from public.profiles p
  order by p.created_at desc;
end;
$$;

revoke execute on function public.admin_list_profiles() from public, anon;
grant execute on function public.admin_list_profiles() to authenticated;

create or replace function public.admin_set_role(
  target_user_id uuid,
  new_role text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'Acceso restringido: se requiere rol admin';
  end if;

  if new_role not in ('user', 'premium', 'admin') then
    raise exception 'Rol no válido';
  end if;

  update public.profiles
  set role = new_role
  where id = target_user_id;

  return found;
end;
$$;

revoke execute on function public.admin_set_role(uuid, text) from public, anon;
grant execute on function public.admin_set_role(uuid, text) to authenticated;

-- El primer administrador se asigna exclusivamente desde SQL Editor:
-- update public.profiles
-- set role = 'admin'
-- where id = (
--   select id from auth.users where email = 'TU_EMAIL'
-- );


-- =========================================================
-- Perfil del usuario y ahorro personal
-- =========================================================
create or replace function public.update_my_profile(new_full_name text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'Sesión requerida';
  end if;
  if length(trim(coalesce(new_full_name, ''))) < 2 or length(trim(new_full_name)) > 80 then
    raise exception 'El nombre debe tener entre 2 y 80 caracteres';
  end if;
  update public.profiles
  set full_name = trim(new_full_name)
  where id = auth.uid();
  return found;
end;
$$;

revoke execute on function public.update_my_profile(text) from public, anon;
grant execute on function public.update_my_profile(text) to authenticated;

create table if not exists public.savings_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  month date not null,
  amount numeric(10,2) not null default 0 check (amount >= 0 and amount <= 100000),
  note text,
  created_at timestamptz not null default now(),
  unique(user_id, month)
);

alter table public.savings_records enable row level security;
revoke all on public.savings_records from anon;
revoke all on public.savings_records from authenticated;
grant select, insert, update, delete on public.savings_records to authenticated;
grant usage, select on sequence public.savings_records_id_seq to authenticated;

drop policy if exists "Users can view own savings" on public.savings_records;
create policy "Users can view own savings"
on public.savings_records for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own savings" on public.savings_records;
create policy "Users can insert own savings"
on public.savings_records for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own savings" on public.savings_records;
create policy "Users can update own savings"
on public.savings_records for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own savings" on public.savings_records;
create policy "Users can delete own savings"
on public.savings_records for delete to authenticated
using (auth.uid() = user_id);


-- ============================================================
-- 13. RESULTADOS GUARDADOS DE CALCULADORAS
-- ============================================================

create table if not exists public.calculator_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  calculator_key text not null,
  calculator_name text not null,
  month date not null default date_trunc('month', now())::date,
  monthly_cost numeric(10,2) not null default 0 check (monthly_cost >= 0 and monthly_cost <= 100000),
  annual_cost numeric(10,2) not null default 0 check (annual_cost >= 0 and annual_cost <= 1200000),
  monthly_saving numeric(10,2) not null default 0 check (monthly_saving >= 0 and monthly_saving <= 100000),
  annual_saving numeric(10,2) not null default 0 check (annual_saving >= 0 and annual_saving <= 1200000),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.calculator_results enable row level security;
revoke all on table public.calculator_results from anon;
revoke all on table public.calculator_results from authenticated;
grant select, insert, delete on table public.calculator_results to authenticated;
grant usage, select on sequence public.calculator_results_id_seq to authenticated;

drop policy if exists "Users can view own calculator results" on public.calculator_results;
create policy "Users can view own calculator results" on public.calculator_results for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own calculator results" on public.calculator_results;
create policy "Users can insert own calculator results" on public.calculator_results for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own calculator results" on public.calculator_results;
create policy "Users can delete own calculator results" on public.calculator_results for delete to authenticated using ((select auth.uid()) = user_id);

create index if not exists idx_calculator_results_user_created on public.calculator_results(user_id, created_at desc);
create index if not exists idx_calculator_results_user_calculator on public.calculator_results(user_id, calculator_key);

-- ============================================================
-- FIN DEL ESQUEMA
-- ============================================================
