-- AHORRAENCASAYA - SUSCRIPCIONES PREMIUM (ESQUEMA ACTUAL)
-- Fuente de referencia alineada con supabase/schema.sql.
-- El navegador solo puede leer suscripciones propias; las escrituras futuras
-- deben realizarse desde un webhook/servidor con credenciales privadas.

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'stripe' check (provider in ('stripe')),
  provider_customer_id text,
  provider_subscription_id text unique,
  provider_price_id text,
  status text not null default 'incomplete',
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  trial_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, provider)
);

create index if not exists idx_subscriptions_user_status on public.subscriptions(user_id, status);
create index if not exists idx_subscriptions_customer on public.subscriptions(provider_customer_id);

alter table public.subscriptions enable row level security;
revoke all on public.subscriptions from anon;
revoke all on public.subscriptions from authenticated;
grant select on public.subscriptions to authenticated;

drop policy if exists "Users can view own subscriptions" on public.subscriptions;
create policy "Users can view own subscriptions" on public.subscriptions
for select to authenticated using (auth.uid() = user_id);

drop policy if exists "Admins can read all subscriptions" on public.subscriptions;
create policy "Admins can read all subscriptions" on public.subscriptions
for select to authenticated using (public.is_admin());

create or replace function public.has_active_premium()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.subscriptions s
    where s.user_id = auth.uid()
      and s.status in ('active','trialing')
      and (s.current_period_end is null or s.current_period_end > now())
  ) or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role in ('premium','admin')
  );
$$;

revoke execute on function public.has_active_premium() from public, anon;
grant execute on function public.has_active_premium() to authenticated;
