-- AHORRAENCASAYA - SUSCRIPCIONES PREMIUM
-- Esta tabla NO debe ser modificada por el navegador.
-- Stripe/Edge Functions actualizarán el estado cuando integremos los pagos.

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  stripe_price_id text,
  status text not null default 'inactive'
    check (status in ('inactive','trialing','active','past_due','canceled','unpaid','incomplete','incomplete_expired')),
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id)
);

alter table public.subscriptions enable row level security;

revoke all on table public.subscriptions from anon;
revoke all on table public.subscriptions from authenticated;

grant select on table public.subscriptions to authenticated;

drop policy if exists "Users can read their own subscription" on public.subscriptions;
create policy "Users can read their own subscription"
on public.subscriptions
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Admins can read all subscriptions" on public.subscriptions;
create policy "Admins can read all subscriptions"
on public.subscriptions
for select
to authenticated
using (public.is_admin());

create index if not exists idx_subscriptions_user_id
on public.subscriptions(user_id);

create index if not exists idx_subscriptions_status
on public.subscriptions(status);